apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: finbif-bib-cron
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            parent: "finbif-bib-update"
        spec:
          containers:
          - name: finbif-bib-update
            image: ghcr.io/luomus/finbif-bib
            env:
            - name: FEED_URL
              value: $FEED_URL
            - name: GIT_EMAIL
              value: $GIT_EMAIL
            - name: GIT_USER
              value: $GIT_USER
            volumeMounts:
              - mountPath: /home/bibuser
                name: finbif-bib-storage
          volumes:
            - name: finbif-bib-storage
              persistentVolumeClaim:
                claimName: finbif-bib-storage
          restartPolicy: OnFailure
